package cn.yulezu.sns.entity;


//Generated 2010-7-26 16:49:25 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

import cn.yulezu.orm.hibernate.BaseEntity;

/**
* Users generated by hbm2java
*/
@Entity
public class Users extends BaseEntity implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	@Column(name="nickname",length=10)
	private String nickname;
	@Column(name="username",length=10)
	private String username;
	@Column(name="password",length=20)
	private String password;
	private Date loginTime;
	private int scope;
	private int integral;
	private int charm;
	private int money;
	private int eash;
	@Column(name="mobile",length=15)
	private String mobile;
	
	@OneToOne(mappedBy="users",cascade={CascadeType.ALL})
	private Userinfo userinfo;
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="hid",nullable=true)
	private Honor honor;//头衔
	
	public Users() {
	}

	public Users(String username, String nickname, String password,
			Date regTime, Date loginTime, int scope, int integral, int charm,
			int money, int eash) {
		this.username = username;
		this.nickname = nickname;
		this.password = password;
		this.loginTime = loginTime;
		this.scope = scope;
		this.integral = integral;
		this.charm = charm;
		this.money = money;
		this.eash = eash;
	}

	public Users(String username,String nickname, String password,
			 Date loginTime, int scope, int integral, int charm,
			int money, int eash, String mobile) {
		this.username = username;
		this.nickname = nickname;
		this.password = password;
		this.loginTime = loginTime;
		this.scope = scope;
		this.integral = integral;
		this.charm = charm;
		this.money = money;
		this.eash = eash;
		this.mobile = mobile;
	}
	
	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	public Honor getHonor() {
		return honor;
	}

	public void setHonor(Honor honor) {
		this.honor = honor;
	}

	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}


	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public int getScope() {
		return this.scope;
	}

	public void setScope(int scope) {
		this.scope = scope;
	}

	public int getIntegral() {
		return this.integral;
	}

	public void setIntegral(int integral) {
		this.integral = integral;
	}

	public int getCharm() {
		return this.charm;
	}

	public void setCharm(int charm) {
		this.charm = charm;
	}

	public int getMoney() {
		return this.money;
	}

	public void setMoney(int money) {
		this.money = money;
	}

	public int getEash() {
		return this.eash;
	}

	public void setEash(int eash) {
		this.eash = eash;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}