package cn.yulezu.sns.entity;

// Generated 2010-7-26 16:49:25 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;


import cn.yulezu.orm.hibernate.BaseEntity;

/**
 * 用户详细信息
 * Userinfo generated by hbm2java
 */
@Entity
public class Userinfo extends BaseEntity implements java.io.Serializable {
	private static final long serialVersionUID = 1L;


	/**
	 * 1是男，0是女
	 */
	private Integer sexy;
	private Integer stature;
	private Date birthday;
	private Integer weight;
	@Column(name="qq",length=20)
	private String qq;
	@Column(name="email",length=30)
	private String email;
	@Column(name="phone",length=15)
	private String phone;
	@Column(name="duty",length=10)
	private String duty;
	@Column(name="hobby",length=10)
	private String hobby;
	@Column(name="blood",length=10)
	private String blood;
	private Integer constellation;
	private Integer marry;
	@Column(name="sign",length=100)
	private String sign;
	
	@OneToOne(cascade={CascadeType.ALL},fetch=FetchType.LAZY,optional=false)
	@JoinColumn(name="uid")
	private Users users;
	//学历
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="eid")
	private Education education;
	//城市
	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="cid")
	private City city;
	public Userinfo() {
	}

	

	public Userinfo( Integer sexy, Integer stature, Date birthday,
			Integer weight, String qq, String email, String phone, String duty,
			String hobby, String blood, Integer constellation,
			Integer marry,  String sign) {

		this.sexy = sexy;
		this.stature = stature;
		this.birthday = birthday;
		this.weight = weight;
		this.qq = qq;
		this.email = email;
		this.phone = phone;
		this.duty = duty;
		this.hobby = hobby;
		this.blood = blood;
		this.constellation = constellation;
		this.marry = marry;

		this.sign = sign;
	}

	
	
	
	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}
	
	
	public Education getEducation() {
		return education;
	}



	public void setEducation(Education education) {
		this.education = education;
	}



	public City getCity() {
		return city;
	}



	public void setCity(City city) {
		this.city = city;
	}



	public Integer getSexy() {
		return this.sexy;
	}

	public void setSexy(Integer sexy) {
		this.sexy = sexy;
	}

	public Integer getStature() {
		return this.stature;
	}

	public void setStature(Integer stature) {
		this.stature = stature;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getDuty() {
		return this.duty;
	}

	public void setDuty(String duty) {
		this.duty = duty;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public String getBlood() {
		return this.blood;
	}

	public void setBlood(String blood) {
		this.blood = blood;
	}

	public Integer getConstellation() {
		return this.constellation;
	}

	public void setConstellation(Integer constellation) {
		this.constellation = constellation;
	}

	public Integer getMarry() {
		return this.marry;
	}

	public void setMarry(Integer marry) {
		this.marry = marry;
	}


	public String getSign() {
		return this.sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

}
