package cn.ss.entity;

// Generated 2010-6-21 8:51:34 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Active generated by hbm2java
 */
public class ActiveLog implements java.io.Serializable {

	private Integer id;
	private SoftwareInfo softwareInfo;
	private Integer number;
	private Date activeTime;
	private double price;

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SoftwareInfo getSoftwareInfo() {
		return softwareInfo;
	}

	public void setSoftwareInfo(SoftwareInfo softwareInfo) {
		this.softwareInfo = softwareInfo;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Date getActiveTime() {
		return this.activeTime;
	}

	public void setActiveTime(Date activeTime) {
		this.activeTime = activeTime;
	}

}
