package cn.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Phoneseries generated by MyEclipse Persistence Tools
 */

public class Phoneseries implements java.io.Serializable {

	// Fields

	/**
	 *系列id
	 */
	private Integer id;

	/**
	 * 系列名称
	 */
	private String name;

	/**
	 * 操作系统
	 */
	private Phoneos os;

	/**
	 * 品牌
	 */
	private Phonebrand brand;

	/**
	 * 创建时间
	 */
	private Date createTime;

	/**
	 * 机型
	 */
	private List<Phonemodel> phoneModelList = new ArrayList<Phonemodel>();

	public List<Phonemodel> getPhoneModelList() {
		return phoneModelList;
	}

	public void setPhoneModelList(List<Phonemodel> phoneModelList) {
		this.phoneModelList = phoneModelList;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Phoneos getOs() {
		return os;
	}

	public void setOs(Phoneos os) {
		this.os = os;
	}

	public Phonebrand getBrand() {
		return brand;
	}

	public void setBrand(Phonebrand brand) {
		this.brand = brand;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}