package cn.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Phoneos generated by MyEclipse Persistence Tools
 */

public class Phoneos implements java.io.Serializable {

	// Fields

	/**
	 * id
	 */
	private Integer id;

	/**
	 *操作系统名称
	 */
	private String name;

	/**
	 * 创建时间
	 */
	private Date createTime;
	/**
	 * 系列
	 */
	private List<Phoneseries> phoneseriesList = new ArrayList<Phoneseries>();

	// Constructors

	public List<Phoneseries> getPhoneseriesList() {
		return phoneseriesList;
	}

	public void setPhoneseriesList(List<Phoneseries> phoneseriesList) {
		this.phoneseriesList = phoneseriesList;
	}

	/** default constructor */
	public Phoneos() {
	}

	/** full constructor */
	public Phoneos(String name, Date createTime) {
		this.name = name;
		this.createTime = createTime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}