package cn.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Phoneos generated by MyEclipse Persistence Tools
 */

public class PhoneOs implements java.io.Serializable {

	// Fields

	/**
	 * id
	 */
	private Integer id;

	/**
	 *操作系统名称
	 */
	private String name;

	/**
	 * 创建时间
	 */
	private Date createTime;
	/**
	 * 系列
	 */
	private List<PhoneSeries> phoneseriesList = new ArrayList<PhoneSeries>();
	/**
	 * 支持的软件
	 */
	private List<Software> softwareList = new ArrayList<Software>();

	/**
	 * 支持的扩展名
	 */
	private List<Extension> extensionList = new ArrayList<Extension>();

	// Constructors

	public List<Extension> getExtensionList() {
		return extensionList;
	}

	public void setExtensionList(List<Extension> extensionList) {
		this.extensionList = extensionList;
	}

	public List<PhoneSeries> getPhoneseriesList() {
		return phoneseriesList;
	}

	public List<Software> getSoftwareList() {
		return softwareList;
	}

	public void setSoftwareList(List<Software> softwareList) {
		this.softwareList = softwareList;
	}

	public void setPhoneseriesList(List<PhoneSeries> phoneseriesList) {
		this.phoneseriesList = phoneseriesList;
	}

	/** default constructor */
	public PhoneOs() {
	}

	/** full constructor */
	public PhoneOs(String name, Date createTime) {
		this.name = name;
		this.createTime = createTime;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}