package cn.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Phonemodel generated by MyEclipse Persistence Tools
 */

public class Phonemodel implements java.io.Serializable {

	// Fields

	/**
	 *id
	 */
	private Integer id;

	/**
	 *机型 名称
	 */
	private String name;

	/**
	 * 系列
	 */
	private Phoneseries phoneseries;
	/**
	 * 品牌
	 */
	private Phonebrand phonebrand;
	/**
	 * 创建时间
	 */
	private Date createTime;
	/**
	 * 支持的软件
	 */
	private List<Softwareinfo> softwareinfoList = new ArrayList<Softwareinfo>();

	// Constructors

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Phoneseries getPhoneseries() {
		return phoneseries;
	}

	public void setPhoneseries(Phoneseries phoneseries) {
		this.phoneseries = phoneseries;
	}

	public Phonebrand getPhonebrand() {
		return phonebrand;
	}

	public void setPhonebrand(Phonebrand phonebrand) {
		this.phonebrand = phonebrand;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public List<Softwareinfo> getSoftwareinfoList() {
		return softwareinfoList;
	}

	public void setSoftwareinfoList(List<Softwareinfo> softwareinfoList) {
		this.softwareinfoList = softwareinfoList;
	}

}