package cn.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Phoneseries generated by MyEclipse Persistence Tools
 */

public class PhoneSeries implements java.io.Serializable {

	// Fields

	/**
	 *系列id
	 */
	private Integer id;

	/**
	 * 系列名称
	 */
	private String name;

	/**
	 * 操作系统
	 */
	private PhoneOs os;

	/**
	 * 品牌
	 */
	private PhoneBrand brand;

	/**
	 * 创建时间
	 */
	private Date createTime;

	/**
	 * 机型
	 */
	private List<PhoneModel> phoneModelList = new ArrayList<PhoneModel>();

	public List<PhoneModel> getPhoneModelList() {
		return phoneModelList;
	}

	public void setPhoneModelList(List<PhoneModel> phoneModelList) {
		this.phoneModelList = phoneModelList;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public PhoneOs getOs() {
		return os;
	}

	public void setOs(PhoneOs os) {
		this.os = os;
	}

	public PhoneBrand getBrand() {
		return brand;
	}

	public void setBrand(PhoneBrand brand) {
		this.brand = brand;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}