package cn.ss.entity;

/**
 * Softwarephone generated by MyEclipse Persistence Tools
 */

public class Softwarephone implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer softwareInfoId;

	private Integer phoneModelId;

	// Constructors

	/** default constructor */
	public Softwarephone() {
	}

	/** full constructor */
	public Softwarephone(Integer softwareInfoId, Integer phoneModelId) {
		this.softwareInfoId = softwareInfoId;
		this.phoneModelId = phoneModelId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSoftwareInfoId() {
		return this.softwareInfoId;
	}

	public void setSoftwareInfoId(Integer softwareInfoId) {
		this.softwareInfoId = softwareInfoId;
	}

	public Integer getPhoneModelId() {
		return this.phoneModelId;
	}

	public void setPhoneModelId(Integer phoneModelId) {
		this.phoneModelId = phoneModelId;
	}

}