package cn.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Softwareinfo generated by MyEclipse Persistence Tools
 */

public class Softwareinfo implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	/**
	 * 软件分类
	 */
	private Softwaretype softearetype;
	/**
	 * 支持机型
	 */
	private List<Phoneos> phoneOsList = new ArrayList<Phoneos>();

	private String description;

	private String imgPath;

	private Integer click;

	private Integer active;

	private Integer download;

	private String downloadPath;

	private String safety;

	private Double traffic;

	private Date createTime;

	private String prompt;

	private Double price;

	private Integer recommend;

	private Integer isShow;

	private Integer plusFine;

	// Constructors

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImgPath() {
		return this.imgPath;
	}

	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public Integer getClick() {
		return this.click;
	}

	public void setClick(Integer click) {
		this.click = click;
	}

	public Integer getActive() {
		return this.active;
	}

	public void setActive(Integer active) {
		this.active = active;
	}

	public Integer getDownload() {
		return this.download;
	}

	public void setDownload(Integer download) {
		this.download = download;
	}

	public String getDownloadPath() {
		return this.downloadPath;
	}

	public void setDownloadPath(String downloadPath) {
		this.downloadPath = downloadPath;
	}

	public String getSafety() {
		return this.safety;
	}

	public void setSafety(String safety) {
		this.safety = safety;
	}

	public Double getTraffic() {
		return this.traffic;
	}

	public void setTraffic(Double traffic) {
		this.traffic = traffic;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getPrompt() {
		return this.prompt;
	}

	public void setPrompt(String prompt) {
		this.prompt = prompt;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Integer getRecommend() {
		return this.recommend;
	}

	public void setRecommend(Integer recommend) {
		this.recommend = recommend;
	}

	public Integer getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	public Integer getPlusFine() {
		return this.plusFine;
	}

	public void setPlusFine(Integer plusFine) {
		this.plusFine = plusFine;
	}

	public Softwaretype getSoftearetype() {
		return softearetype;
	}

	public void setSoftearetype(Softwaretype softearetype) {
		this.softearetype = softearetype;
	}

	public List<Phoneos> getPhoneOsList() {
		return phoneOsList;
	}

	public void setPhoneOsList(List<Phoneos> phoneOsList) {
		this.phoneOsList = phoneOsList;
	}

}