package cn.ss.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Softwaretype generated by MyEclipse Persistence Tools
 */

public class SoftwareType implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private Integer zindex;

	/**
	 * 是否显示0.否，1.是
	 */
	private Integer isShow = 1;

	/**
	 * 创建时间
	 */
	private Date createTime;

	/**
	 * 是否换行0.否，1.是
	 */
	private Integer isWrap = 0;
	/**
	 * 软件信息
	 */
	private List<SoftwareInfo> softwareinfoList = new ArrayList<SoftwareInfo>();

	// Constructors

	/** default constructor */
	public SoftwareType() {
	}

	/** full constructor */
	public SoftwareType(String name, Integer zindex, Integer isShow) {
		this.name = name;
		this.zindex = zindex;
		this.isShow = isShow;
	}

	// Property accessors

	public List<SoftwareInfo> getSoftwareinfoList() {
		return softwareinfoList;
	}

	public void setSoftwareinfoList(List<SoftwareInfo> softwareinfoList) {
		this.softwareinfoList = softwareinfoList;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getZindex() {
		return this.zindex;
	}

	public void setZindex(Integer zindex) {
		this.zindex = zindex;
	}

	public Integer getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Integer isShow) {
		this.isShow = isShow;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getIsWrap() {
		return isWrap;
	}

	public void setIsWrap(Integer isWrap) {
		this.isWrap = isWrap;
	}

}