package cn.ss.entity;

/**
 * Softwarephone generated by MyEclipse Persistence Tools
 */

public class SoftwareOs implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer softwareId;

	private Integer phoneOsId;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSoftwareId() {
		return softwareId;
	}

	public void setSoftwareId(Integer softwareId) {
		this.softwareId = softwareId;
	}

	public Integer getPhoneOsId() {
		return phoneOsId;
	}

	public void setPhoneOsId(Integer phoneOsId) {
		this.phoneOsId = phoneOsId;
	}

}