package cn.ss.entity;

/**
 * Softwarephone generated by MyEclipse Persistence Tools
 */

public class SoftwareOs implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer softwareInfoId;

	private Integer phoneOsId;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSoftwareInfoId() {
		return softwareInfoId;
	}

	public void setSoftwareInfoId(Integer softwareInfoId) {
		this.softwareInfoId = softwareInfoId;
	}

	public Integer getPhoneOsId() {
		return phoneOsId;
	}

	public void setPhoneOsId(Integer phoneOsId) {
		this.phoneOsId = phoneOsId;
	}

}