package cn.ss.entity;

// Generated 2010-6-21 8:51:34 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Downloadlog generated by hbm2java
 */
public class DownloadLog implements java.io.Serializable {

	private Integer id;
	private SoftwareInfo softwareInfo;
	private Date downloadTime;
	private Double downloadPrice;
	private int number;

	public int getNumber() {
		return number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public SoftwareInfo getSoftwareInfo() {
		return softwareInfo;
	}

	public void setSoftwareInfo(SoftwareInfo softwareInfo) {
		this.softwareInfo = softwareInfo;
	}

	public Date getDownloadTime() {
		return this.downloadTime;
	}

	public void setDownloadTime(Date downloadTime) {
		this.downloadTime = downloadTime;
	}

	public Double getDownloadPrice() {
		return this.downloadPrice;
	}

	public void setDownloadPrice(Double downloadPrice) {
		this.downloadPrice = downloadPrice;
	}

}
